### ISSUE TITLE
Long duration of CircleCI builds

### ISSUE THREAD

**Issue by raman-m** [ThreeMammals/Ocelot#2034]
### Expected Behavior
It would be good if build will take no more than 5-6 minutes, less is better.

### Actual Behavior
Success CircleCI build takes around [12-13 minutes](https://app.circleci.com/pipelines/github/ThreeMammals/Ocelot).

The old duration in 2023 for 19.x releases was around 2 minutes only!!! After migration to .NET 8 the duration had increased to ~6 minutes because of 3 SDKs builds. We need to decrease build time down to 6 minutes, but it is better to parallelize the build and decrease overall build time down to 2-3 minutes.

### Long lasting Unit tests, >10 sec
- [Ocelot.UnitTests.Polly](https://github.com/search?q=repo%3AThreeMammals%2FOcelot%20Ocelot.UnitTests.Polly&type=code) namespace: **total 28s**
- [Ocelot.UnitTests.Requester](https://github.com/search?q=repo%3AThreeMammals%2FOcelot+Ocelot.UnitTests.Requester&type=code) namespace: **total 16.5s**

### Long lasting Integration tests, >10 sec
- [AdministrationTests](https://github.com/search?q=repo%3AThreeMammals%2FOcelot+AdministrationTests&type=code) class: **total 11.5s**

### Long lasting Acceptance tests, >10 sec
- [Ocelot.AcceptanceTests.Request](https://github.com/search?q=repo%3AThreeMammals%2FOcelot+Ocelot.AcceptanceTests.Request&type=code) namespace: **total 11.2s**
- [HttpTests](https://github.com/search?q=repo%3AThreeMammals%2FOcelot+HttpTests&type=code) class: total 10.8s
- [EurekaServiceDiscoveryTests](https://github.com/search?q=repo%3AThreeMammals%2FOcelot+EurekaServiceDiscoveryTests&type=code) class: **total 26.3s** ❗ 
- [PollyQoSTests](https://github.com/search?q=repo%3AThreeMammals%2FOcelot+PollyQoSTests&type=code) class: **total 1.8 min**❗❗

### Specifications
  - Version: **23.2.2**
  - Subsystem: CircleCI

**Comment by raman-m** [comment]
### TODO
- [x] **Part 1**. Done! ✔️ commit https://github.com/ThreeMammals/Ocelot/commit/59b63eab9c2cd2ab33c5752bbc3bd00a079cd74c
- [ ] **Part 2**. See more in https://github.com/ThreeMammals/Ocelot/pull/2045#issuecomment-2052047191
- [ ] **Remove BDDfy from [unit tests](https://github.com/search?q=repo%3AThreeMammals%2FOcelot+.BDDfy%28%29%3B+path%3A%2F%5Etest%5C%2FOcelot.UnitTests%5C%2F%2F&type=code)**. In favor of AAA-pattern with xUnit. Optional, but very desired...
